source("../DTU-DADS-ASF/sourceASF.R")
sourceASF()
indexHerdFile<-read.table("../ASFinputs/IndexHerds.csv",sep=";")
optC<-ASFoptions(maxTime=365,n=1000,indexHerdSelect=list(ID=indexHerdFile[[1]]),interventionFunctions=c("CullRing(1,2,2)"),runID="AODep2Det1km",seed=-10)
a<-ASF(optC)
