source("../DTU-DADS-ASF/sourceASF.R")
sourceASF()
indexHerdFile<-read.table("../ASFinputs/IndexHerds.csv",sep=";")
optC<-ASFoptions(maxTime=365,n=1000,indexHerdSelect=list(ID=indexHerdFile[[1]]),SerologyTesting=c(1,4,5,6),PCRTesting=c(2,5,6),runID="AOSerSV2PCRPV1",seed=-10)
a<-ASF(optC)
